# Generated by Django 5.1 on 2024-09-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcat',
            name='product_image',
            field=models.ImageField(default='', upload_to='products/product_image'),
        ),
    ]
